export const appRoutes = {
  login: '/(auth)/login',
  dashboard: '/(tabs)/dashboard',
  medicines: '/(tabs)/medicines',
  medicineAdd: '/(tabs)/medicines/add',
  medicineExpiry: '/(tabs)/medicines/expiry',
  inventory: '/(tabs)/inventory',
  inventoryAdd: '/(tabs)/inventory/add',
  inventoryLowStock: '/(tabs)/inventory/low-stock',
  inventoryExpiry: '/(tabs)/inventory/expiry',
  inventoryMovements: '/(tabs)/inventory/movements',
  sales: '/(tabs)/sales',
  salesCheckout: '/(tabs)/sales/checkout',
  salesHistory: '/(tabs)/sales/history',
  more: '/(tabs)/more',
  reports: '/(tabs)/more/reports',
  suppliers: '/(tabs)/more/suppliers',
  supplierAdd: '/(tabs)/more/suppliers/add',
  purchases: '/(tabs)/more/purchases',
  purchaseAdd: '/(tabs)/more/purchases/add',
  users: '/(tabs)/more/users',
  userAdd: '/(tabs)/more/users/add',
  reviews: '/(tabs)/more/reviews',
  reviewAdd: '/(tabs)/more/reviews/add',
  } as const;
